PruebaDF/Models/Estudiante.cs
using System;
using System.Collections.Generic;

namespace PruebaDF.Models;

public partial class Estudiante
{
    public int EstudianteId { get; set; }

    public string Nombre { get; set; } = null!;

    public int? Documento { get; set; }

    public string Correo { get; set; } = null!;

    public virtual ICollection<MateriasEstudiante> MateriasEstudiantes { get; set; } = new List<MateriasEstudiante>();

}

PruebaDF/Controllers/EstudiantesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PruebaDF.Models;

namespace PruebaDF.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly PruebaDfContext _context;

        public EstudiantesController(PruebaDfContext context)
        {
            _context = context;
        }

        // GET: Estudiantes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estudiantes.ToListAsync());
        }

        // GET: Estudiantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.EstudianteId == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Estudiantes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EstudianteId,Nombre,Documento,Correo")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EstudianteId,Nombre,Documento,Correo")] Estudiante estudiante)
        {
            if (id != estudiante.EstudianteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.EstudianteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.EstudianteId == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante != null)
            {
                _context.Estudiantes.Remove(estudiante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
            return _context.Estudiantes.Any(e => e.EstudianteId == id);
        }
    }
}

PruebaDF/Controllers/MateriasEstudiantesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PruebaDF.Models;
using PruebaDF.Repository.Interfaces;

namespace PruebaDF.Controllers
{
    public class MateriasEstudiantesController : Controller
    {
        public  IMateriasEstudianteRepository _materiasEstudianteRepo { get; set; }

        public MateriasEstudiantesController( IMateriasEstudianteRepository materiasEstudianteRepo )
        {
            _materiasEstudianteRepo = materiasEstudianteRepo;
        }

        // GET: MateriasEstudiantes
        public IActionResult Index(int? id)
        {
            var materiasEstudiante = _materiasEstudianteRepo.ObtenerMateriasEstudianteId(id);

            ViewBag.IdEstudiante = id;
            ViewBag.Message = TempData["Message"];

            return View(materiasEstudiante);
        }

        // GET: MateriasEstudiantes/Details/5
        public IActionResult Details(int? id, int? idMat)
        {
            if (id == null)
            {
                return NotFound();
            }

            var materiasEstudiante =  _materiasEstudianteRepo.ObtenerMateriasEstudianteAsociadas(id, idMat);

            if (materiasEstudiante == null)
            {
                return NotFound();
            }

            return View(materiasEstudiante);
        }

        // GET: MateriasEstudiantes/Create
        public IActionResult Create(int? idEst)
        {            
            var materiasEstudiante = _materiasEstudianteRepo.ObtenerMateriasAsociar(idEst);

            ViewBag.IdEstudiante = idEst;

            if (materiasEstudiante != null && materiasEstudiante.Any())
            {
                var estudianteSeleccionado = _materiasEstudianteRepo.ObtenerEstudianteSeleccionado(idEst);

                ViewData["EstudianteId"] = new SelectList(estudianteSeleccionado, "EstudianteId", "Nombre");
                ViewData["MateriaId"] = new SelectList(materiasEstudiante, "MateriaId", "NombreCreditos");
            }
            else
            {
                TempData["Message"] = _materiasEstudianteRepo.ObtenerMensajeMateriasAsociadas();
                return RedirectToAction("Index", new { id = idEst });
            }

            return View();
        }

        // POST: MateriasEstudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EstudianteId,MateriaId")] MateriasEstudiante materiasEstudiante)
        {
            if (ModelState.IsValid)
            {
                if (_materiasEstudianteRepo.AsociarMateria(materiasEstudiante.EstudianteId, materiasEstudiante.MateriaId))
                {
                     _materiasEstudianteRepo.Crear(materiasEstudiante);
                    await _materiasEstudianteRepo.SaveAsync();
                    return RedirectToAction("Index",new { id = materiasEstudiante.EstudianteId });
                }
                else
                {
                    TempData["Message"] = _materiasEstudianteRepo.ObtenerMensajeMateriasCreditos(); 
                    return RedirectToAction("Index", new { id = materiasEstudiante.EstudianteId });            
                }
            }
            return View(materiasEstudiante);
        }

        // GET: MateriasEstudiantes/Edit/5
        public IActionResult Edit(int id, int idMat)
        {
            ViewBag.IdEstudiante = id;

            var materiasEstudiante =  _materiasEstudianteRepo.ObtenerMateriasEstudianteAsociadas(id, idMat);

            if (materiasEstudiante == null)
            {
                return NotFound();
            }
            var estudianteAsociado = new List<Estudiante?>{materiasEstudiante.Estudiante};
            var materiasPorAsociar = _materiasEstudianteRepo.ObtenerMateriasEditar(id, idMat);

            ViewData["EstudianteId"] =  new SelectList(estudianteAsociado, "EstudianteId", "Nombre");
            ViewData["MateriaId"] = new SelectList(materiasPorAsociar, "MateriaId", "NombreCreditos", idMat);

            return View(materiasEstudiante);
        }

        // POST: MateriasEstudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int idMat, [Bind("EstudianteId,MateriaId")] MateriasEstudiante materiasEstudiante)
        {
            if (id != materiasEstudiante.EstudianteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {          
                    if (_materiasEstudianteRepo.AsociarMateria(id, idMat))
                    {
                        _materiasEstudianteRepo.Actualizar(id, materiasEstudiante.MateriaId, idMat);
                        await _materiasEstudianteRepo.SaveAsync();
                        return RedirectToAction("Index", new { id });
                    }
                    else
                    {
                        TempData["Message"] = _materiasEstudianteRepo.ObtenerMensajeMateriasCreditos();
                        return RedirectToAction("Index", new { id });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    var materiaEstudianteExiste =  _materiasEstudianteRepo.ObtenerMateriasEstudianteId(materiasEstudiante.EstudianteId);
                   
                    if (!materiaEstudianteExiste.Any())
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(materiasEstudiante);
        }

        // GET: MateriasEstudiantes/Delete/5
        public IActionResult Delete(int? id, int? idMat)
        {
            if (id == null)
            {
                return NotFound();
            }

            var materiasEstudiante =  _materiasEstudianteRepo.ObtenerMateriasEstudianteAsociadas(id, idMat);

            if (materiasEstudiante == null)
            {
                return NotFound();
            }

            return View(materiasEstudiante);
        }

        // POST: MateriasEstudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int idMat)
        {
            var materiasEstudiante = new MateriasEstudiante
            {
                EstudianteId = id,
                MateriaId = idMat
            };
            
            _materiasEstudianteRepo.Eliminar(materiasEstudiante);
            await _materiasEstudianteRepo.SaveAsync();
            return RedirectToAction("Index", new { id });
        }              
    }
}

PruebaDF/Views/Estudiantes/Create.cshtml
@model PruebaDF.Models.Estudiante

@{
    ViewData["Title"] = "Create";
}

<h1> Crear Estudiante</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PruebaDF/Views/Estudiantes/Delete.cshtml
@model PruebaDF.Models.Estudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Estudiante</h1>
<h2>¿Está seguro de que desea eliminar el estudiante?</h2>
<hr />

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
    </dl>
    <div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="EstudianteId" />
            <input type="submit" value="Eliminar" class="btn btn-danger" /> 
            <a class="btn btn-secondary" asp-action="Index">Volver</a>
        </form>
    </div>   
</div>

PruebaDF/Views/Estudiantes/Details.cshtml
@model PruebaDF.Models.Estudiante

@{
    ViewData["Title"] = "Details";
}

<h1>Información del Estudiante</h1>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.EstudianteId">Modificar</a> 
    <a class="btn btn-secondary" asp-action="Index">Volver</a>
</div>

PruebaDF/Views/Estudiantes/Edit.cshtml
@model PruebaDF.Models.Estudiante

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar Estudiante</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EstudianteId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Volver</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PruebaDF/Views/Estudiantes/Index.cshtml
@model IEnumerable<PruebaDF.Models.Estudiante>

@{
    ViewData["Title"] = "Index";
}

<h1>Estudiante</h1>

<div class="row justify-content-end">
    <div class="col-md-4">
        <a class="btn btn-primary" role="button" asp-action="Create">Crear</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.EstudianteId">Modificar</a> 
                <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.EstudianteId">Ver Detalle</a> 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.EstudianteId">Eliminar</a> 
                <a class="btn btn-success" asp-action="Index" asp-controller="MateriasEstudiantes" asp-route-id="@item.EstudianteId">Asociar Materias</a>
            </td>
        </tr>
}
    </tbody>
</table>